# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('bedcollr_rcpparma_hello_world', PACKAGE = 'bedcollr')
}

testarma <- function() {
    .Call('bedcollr_testarma', PACKAGE = 'bedcollr')
}

rcpparma_outerproduct <- function(x) {
    .Call('bedcollr_rcpparma_outerproduct', PACKAGE = 'bedcollr', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('bedcollr_rcpparma_innerproduct', PACKAGE = 'bedcollr', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('bedcollr_rcpparma_bothproducts', PACKAGE = 'bedcollr', x)
}

